format_version: 2
pipelines:
  chart-minio-test:
    group: chart-minio
    label_template: "${git-chart-minio[:8]}"
    lock_behavior: unlockWhenFinished
    timer:
      spec: "* * * * * ? */15"
      only_on_changes: yes
    materials:
      git-chart-minio:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: git@git.k8s.fscker.org:helm-charts/minio.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables:
      CHART_NAME: minio
    stages:
      - tests:
          jobs:
            lint:
              tasks:
                - script: |
                    set -e

                    helm lint ./helm-charts/${CHART_NAME}

      - dummy-stage:
          tasks:
            - script: |
                set -e

                export GIT_BRANCH="${GO_SCM_GIT_CHART_MINIO_CURRENT_BRANCH}"

                if [ "$GIT_BRANCH" != "master" ]; then
                  curl "${GO_SERVER_URL}/api/stages/${GO_PIPELINE_NAME}/${GO_STAGE_NAME}/cancel" \
                    -u "${GO_AUTOMATION_USER}:${GO_AUTOMATION_PASSWORD}" \
                    -H 'Confirm: true' \
                    -X POST \
                    -k
                fi

  chart-minio-build:
    group: chart-minio
    label_template: "0.1.${COUNT}-${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: chart-minio-test
        stage: dummy-stage
      git-chart-minio:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: git@git.k8s.fscker.org:helm-charts/minio.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables:
      CHART_NAME: minio
    secure_variables:
      GITHUB_TOKEN: AES:C/Kze4KS3Nj7IIqRJcP7HQ==:5oIutnej0aAQKMna7JzuFD3vaEs/2nwjT+JmJG6b4CPcpwssLOFVotNMatN7VIaCNcYlE7XnmVG/kERl3CTATi314X8ZAYymNm2LvqUk2hWwj0HgEthbw/4FdIeZ57uF
    stages:
      - package:
          jobs:
            package:
              tasks:
                - script: |
                    set -e
                    helm package --version "$(echo $GO_PIPELINE_LABEL | awk -F '-' '{print $1}')" ./helm-charts/${CHART_NAME}

                    bash ./upload-chart.sh minio-*.tgz

              artifacts:
                - build:
                    source: minio-*.tgz
                    destination: ./chart/
