apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
stringData:
{{- range $key, $value := .Values.config.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
