apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: http-server
      protocol: TCP
      name: http-server
    - port: {{ .Values.service.ui.port }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui

  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
